DROP TABLE foodItem;

CREATE TABLE foodItem(
    foodItemId number(11)    NOT NULL,
    foodItemName varchar(50) NOT NULL,
    foodDesc varchar(250),
    PRIMARY KEY (foodItemId)
);


insert into foodItem values(1001,'Signature Quattro Beef (Classic)','Beef pizza 4 favorite');
insert into foodItem values(1002,'Signature Quattro Chicken (Classic)','Chicken pizza 4 favorite');
insert into foodItem values(1003,'Vegie Quattro (Favorites)','Vegie pizza 4 favorite');
insert into foodItem values(1004,'BBQ Chicken','Succulent shredded chicken, fresh onions, green pepper topped with 100% mozzarella cheese n tangy bbq sauce');
insert into foodItem values(1005,'Smoky beef n chick','Onion slices, green peppers, ground beef and chicken potpourri sausages on our awesome smoky blended bbq sauce');
insert into foodItem values(1006,'Chicken Wings Plain','Well seasoned roasted chicken wings, tender and juicy');
insert into foodItem values(1007,'Breadstix','Sink your teeth into 8 baked treats filled with garlic goodness');
insert into foodItem values(1008,'Blueberry Cheesecake Lava Cake','A creamy cheesecake filled with luscious, warm sauce.');
insert into foodItem values(1009,'Chocolate Lava Cake','Discover a lusciously melted soft chocolate centre, overflowing with chocolatey ');
insert into foodItem values(1010,'Pepsi (bottle)','Pepsi');
insert into foodItem values(1011,'Eggplant Fried Egg Rice','Fried Egg, Eggplant, Rice');
insert into foodItem values(1012,'Lemon Crispy Chicken Rice','Lemon, Chicken, Rice');
insert into foodItem values(1013,'Mushroom Soup','Soup, mushroom');
insert into foodItem values(1014,'Cornflake Fish Finger Salad ','Cornflake, Fish, Salad');
insert into foodItem values(1015,'Delight Gallery Sandwish','Sandwish');
insert into foodItem values(1016,'Bologness Seafood Spacghetti','Spacghetti, Seafood');
insert into foodItem values(1017,'Aglio Olio Spaghetti with fish','Fish, Spaghetti ');
insert into foodItem values(1018,'Mozzarela Cheese Fish Chop','Fish Chop, Cheese');
insert into foodItem values(1019,'Fish Fillet Bucket Rice','Fish, Rice');
insert into foodItem values(1020,'Coffee Ice','Iced coffee');
insert into foodItem values(1021,'Salted Crispy Chicken Rice ','Chicken, Rice, Crispy');
insert into foodItem values(1022,'Fried Chicken Chop Rice','Chicken Chop with Rice');
insert into foodItem values(1023,'Taiwan Railway Bento Rice','Taiwan food');
insert into foodItem values(1024,'Cheesy Pork Chop Rice','Pork Chop Rice with cheese');
insert into foodItem values(1025,'Minced Meat Ramen','Ramen with Minced Meat ');
insert into foodItem values(1026,'Braised Pork Chop Ramen','Ramen with Braised Pork Chop ');
insert into foodItem values(1027,'Chicken Chop ramen','Ramen with Chicken Chop ');
insert into foodItem values(1028,'Crispy Chicken Chop','Chicken Chop, Crispy ');
insert into foodItem values(1029,'Fried Dumpling','Delicious fried dumpling');
insert into foodItem values(1030,'Asam Milk Tea','Asam Milk Tea');
insert into foodItem values(1031,'Chicken Macaroni Cheese','Chicken Macaroni with Cheese');
insert into foodItem values(1032,'Kenny''s Homemade Muffin','Muffin, Homemade');
insert into foodItem values(1033,'Coleslaw','Coleslaw');
insert into foodItem values(1034,'Crips Garden Salad','Garden Salad');
insert into foodItem values(1035,'Kenny''s A la Carte Chicken','Chicken');
insert into foodItem values(1036,'Macaroni n Cheese','Macaroni n Cheese');
insert into foodItem values(1037,'Mashed Potato n gravy','Mashed Potato with gravy');
insert into foodItem values(1038,'Aromatic Rice','Aromatic Rice');
insert into foodItem values(1039,'Joybean Original','Joybean Original');
insert into foodItem values(1040,'Mango Juice','Mango Juice');
insert into foodItem values(1041,'Zinger Cheezy','Zinger Cheezy');
insert into foodItem values(1042,'Zinger Cheezy BBQ','Zinger Cheezy BBQ');
insert into foodItem values(1043,'Potato Wedges of Fries','Potato Wedges of Fries');
insert into foodItem values(1044,'Whipped Potato','Whipped Potato');
insert into foodItem values(1045,'Coleslaw','Coleslaw');
insert into foodItem values(1046,'One piece of chiecken','One piece of chiecken');
insert into foodItem values(1047,'Fries','Fries');
insert into foodItem values(1048,'Rice','Rice');
insert into foodItem values(1049,'Pepsi','Pepsi');
insert into foodItem values(1050,'Pepsi black','Pepsi black');
insert into foodItem values(1051,'Big Mac','Two all-beef patties with lettuce, onions, pickles, cheese and special sauce in a toasted sesame seed bun.');
insert into foodItem values(1052,'Beef Burger','Pure beef patty, onions, pickles, ketchup and mustard in a toasted bun.');
insert into foodItem values(1053,'Cheeseburger','Complement the taste and pure Beef Burger with a slice of cheese.');
insert into foodItem values(1054,'McChicken','Your favorite chicken burger cooked to golden perfection topped with lettuce and special sauce.');
insert into foodItem values(1055,'Filet-O-Fish','A classic favourite of a fish burger served with tartar sauce and cheddar cheese in a steamed bun.');
insert into foodItem values(1056,'Bubur Ayam McD','Juicy chicken strips in mouth-watering porridge, garnished with spring onions, sliced ginger, fried shallots and diced chilies. Just like mum''s cooking!');
insert into foodItem values(1057,'Spicy chicken McDeluxe','Specially marinated whole chicken thigh meat with a delightfully crispy coat, layered with fresh lettuce and special sauce in a corn meal bun.');
insert into foodItem values(1058,'French Fries','We only use premium Russet Burbank variety potatoes for that fluffy inside, crispy outside taste of our world-famous fries.');
insert into foodItem values(1059,'Apple Pie','Crispy pie crust with tasty apple chunks.');
insert into foodItem values(1060,'Iced Milo','Theres nothing like an icy drink full of chocolate and malt flavours.');
insert into foodItem values(1061,'Roti Sosej Biasa','Sosej ni adalah makanan yang diperbuat daripada daging kisar (ayam, lembu, kambing dan sebagainya)');
insert into foodItem values(1062,'Roti Sosej Special','Tambah telur');
insert into foodItem values(1063,'Burger Ayam Biasa','Resipi sedap dan mudah');
insert into foodItem values(1064,'Burger Ayam Special','Tambah telur');
insert into foodItem values(1065,'Burger Ayam Double','Tambah lagi satu daging, double sedap');
insert into foodItem values(1066,'Burger Ayam Double Special','Tambah telur');
insert into foodItem values(1067,'Oblong Biasa','Burger but the shape is oblong');
insert into foodItem values(1068,'Oblong Special','Tambah telur');
insert into foodItem values(1069,'Benjo Biasa','Benjo more gooding and juicier than telur biasa');
insert into foodItem values(1070,'Benjo Special','Tambah telur');
insert into foodItem values(1071,'Sweet n Sour Sauce','Comes with steamed rice');
insert into foodItem values(1072,'Black Pepper Sauce','Comes with steamed rice');
insert into foodItem values(1073,'Malaysian Curry','Comes with steamed rice');
insert into foodItem values(1074,'Garlic Sauce','Comes with steamed rice');
insert into foodItem values(1075,'Ginger Sauce','Comes with steamed rice');
insert into foodItem values(1076,'Thai Chilli Sauce','Comes with steamed rice');
insert into foodItem values(1077,'Special Fried Rice','Mixture of seafood');
insert into foodItem values(1078,'Honey Lemon Ice','Lemon ice with honey');
insert into foodItem values(1079,'Pepsi ','Soft drinks');
insert into foodItem values(1080,'Orange Juice','Fresh juice');
insert into foodItem values(1081,'Sup Ayam','Chicken soup is a soup made from chicken');
insert into foodItem values(1082,'Sup Cendawan','Mushroom soup is a soup made from mushroom');
insert into foodItem values(1083,'Sup Udang','Prawn soup is a soup made from prawn');
insert into foodItem values(1084,'Tom Yam Cendawan','Tom Yam Mushroom is a Tom Yam soup add-on Mushroom ');
insert into foodItem values(1085,'Tom Yam Seafood','Tom Yam Seafood is a Tom Yam soup add-on Seafood');
insert into foodItem values(1086,'Sup Daging','Meat soup is a soup made from different mix fo meat');
insert into foodItem values(1087,'Kailan Ikan Masin','One type of vegetable fried with salty fish');
insert into foodItem values(1088,'Kangkung Goreng Belacan','One type of vegetable fried with Belacan');
insert into foodItem values(1089,'Kerabu Maggi','Instant Noodles with Malaysian cuisine dish style');
insert into foodItem values(1090,'Kerabu Seafood','Malaysian cuisine dish style with seafood');
insert into foodItem values(1091,'1/4 Ayam','quarter of a chicken');
insert into foodItem values(1092,'Nasi','rice');
insert into foodItem values(1093,'Kubis','Cabbage');
insert into foodItem values(1094,'Timun','Timun');
insert into foodItem values(1095,'Tauhu','Tauhu');
insert into foodItem values(1096,'Tempe','Tempe');
insert into foodItem values(1097,'Hati','Heart');
insert into foodItem values(1098,'Air Tin','canned drinks');
insert into foodItem values(1099,'Watermelon Juice','Fresh Juice');
insert into foodItem values(1100,'Hoeny Lemon Ice','Lemon ice with honey');
insert into foodItem values(1101,'Taiwanese Signature Braised Pork Rice','Japan pearl rice, taiwan pickle');
insert into foodItem values(1102,'Taiwanese Signature Braised Homemade Noodle','Homemade noodle,taiwan sausage');
insert into foodItem values(1103,'Taiwanese Salt and Pepper Fried Pork Chop Rice','Japan pearl rice, taiwan pickle');
insert into foodItem values(1104,'Taiwanese Fish and Chips','Taiwanese Fish and Chips');
insert into foodItem values(1105,'Butter Chicken Rice','Butter Chicken Rice');
insert into foodItem values(1106,'Marmite Chicken Rice','Marmite Chicken Rice');
insert into foodItem values(1107,'Cheesy Crispy Chicken Rice Set','NEW cheesy crispy chicekn braised egg braised rice french Fries');
insert into foodItem values(1108,'Braised Egg','Braised Egg');
insert into foodItem values(1109,'Braised Taufu','Braised Taufu');
insert into foodItem values(1110,'Red Tea','Red Tea');
insert into foodItem values(1111,'Salted Egg Burger','Salted Egg Burger');
insert into foodItem values(1112,'French fries','French fries');
insert into foodItem values(1113,'mashed potato','mashed potato');
insert into foodItem values(1114,'vegetable salad','vegetable salad');
insert into foodItem values(1115,'Chicken Burger','Chicken Burger');
insert into foodItem values(1116,'Fish ''n'' Chips','Fish ''n'' Chips');
insert into foodItem values(1117,'Nasi Ayam MB™','Nasi Ayam MB™');
insert into foodItem values(1118,'Bubur Ayam MB™','Bubur Ayam MB™');
insert into foodItem values(1119,'Chick-O-Rice','Chick-O-Rice');
insert into foodItem values(1120,'Chicken Nuggets','Chicken Nuggets');
insert into foodItem values(1121,'Roti Canai','Roti Canai');
insert into foodItem values(1122,'Roti Telur','Roti Telur');
insert into foodItem values(1123,'Roti Telur Bawang','Roti Telur Bawang');
insert into foodItem values(1124,'Fried Chicken','Fried Chicken');
insert into foodItem values(1125,'Fried Fish','Fried Fish');
insert into foodItem values(1126,'Boiled Egg','Boiled Egg');
insert into foodItem values(1127,'Egg Omelette','Egg Omelette');
insert into foodItem values(1128,'Chicken Varuval','Chicken Varuval');
insert into foodItem values(1129,'Chicken Paratel','Chicken Paratel');
insert into foodItem values(1130,'Vegetarian Mee Hoon Goreng','Vegetarian Mee Hoon Goreng');
insert into foodItem values(1131,'Steam Chicken Rice','Rice with steam chicken on top');
insert into foodItem values(1132,'Roaster Chicken Rice','Rice with Roaster chicken on top');
insert into foodItem values(1133,'Rice','Rice');
insert into foodItem values(1134,'Kopi','Beverage');
insert into foodItem values(1135,'Kopi O','Beverage');
insert into foodItem values(1136,'Tea C','Beverage');
insert into foodItem values(1137,'Tea C','Beverage');
insert into foodItem values(1138,'Barli Lemon','Beverage');
insert into foodItem values(1139,'Tea O','Beverage');
insert into foodItem values(1140,'Tea O Lemon','Beverage');
insert into foodItem values(1141,'Nasi Briyani Kambing','Nasi Briyani Kambing');
insert into foodItem values(1142,'Nasi Briyani Ayam Goreng','Nasi Briyani Ayam Goreng');
insert into foodItem values(1143,'Nasi Briyani Ayam Kurma','Nasi Briyani Ayam Kurma');
insert into foodItem values(1144,'Nasi Briyani Ayam Madu','Nasi Briyani Ayam Madu');
insert into foodItem values(1145,'Nasi Briyani Ayam Kicap','Nasi Briyani Ayam Kicap');
insert into foodItem values(1146,'Nasi KandarnSayur Daging','Nasi KandarnSayur Daging');
insert into foodItem values(1147,'Nasi KandarnSayur Kambing','Nasi KandarnSayur Kambing');
insert into foodItem values(1148,'Nasi KandarnSayur Ayam Madu','Nasi KandarnSayur Ayam Madu');
insert into foodItem values(1149,'Nasi KandarnSayur Kambing Bruit','Nasi KandarnSayur Kambing Bruit');
insert into foodItem values(1150,'Nasi Kandarn Sayur Ikan Kompung','Nasi Kandarn Sayur Ikan Kompung');
insert into foodItem values(1151,'Tembikai Potong','Fresh fruits');
insert into foodItem values(1152,'Nenas Potong','Fresh fruits');
insert into foodItem values(1153,'Mangga Potong','Fresh fruits');
insert into foodItem values(1154,'Buah Campur Potong','Fresh fruits');
insert into foodItem values(1155,'BBQ Chicken Wing','BBQ Chicken Wing');
insert into foodItem values(1156,'Black Pepper Sauce','Black Pepper Sauce');
insert into foodItem values(1157,'Buffalo Wing','An unbreaded chicken wing section that is generally deep-fried');
insert into foodItem values(1158,'Burger Ayam','Burger Chicken');
insert into foodItem values(1159,'Burger Daging Special','Burger Chicken with egg');
insert into foodItem values(1160,'Cheese Wedges','Cheese Fried Wedges');
insert into foodItem values(1161,'Sup Ayam','Sup Ayam');
insert into foodItem values(1162,'Sup Daging','Sup Daging');
insert into foodItem values(1163,'Sup Tulang','Sup Tulang');
insert into foodItem values(1164,'Sup Ekor','Sup Ekor');
insert into foodItem values(1165,'Sup Campur','Sup Campur');
insert into foodItem values(1166,'Tomyam Ayam','Tomyam Ayam');
insert into foodItem values(1167,'Tomyam Daging','Tomyam Daging');
insert into foodItem values(1168,'Tomyam Campur','Tomyam Campur');
insert into foodItem values(1169,'Tomyam Seafood','Tomyam Seafood');
insert into foodItem values(1170,'Ayam Kunyit','Ayam Kunyit');
insert into foodItem values(1171,'Single Regular Cup','4 oz scoop. 1 flavor');
insert into foodItem values(1172,'Handpacked Pint','350gm');
insert into foodItem values(1173,'Handpacked Quart','700gm. Maximum 2 flavors per quart.');
insert into foodItem values(1174,'Twinpack Pint','2 Pints. 2 x 350gm. Maximum 2 flavors per pint.');
insert into foodItem values(1175,'Twinpack Quart','2 Quarts. 2 x 700gm. Maximum 2 flavours per quart.');
insert into foodItem values(1176,'Handpacked Half Gallon','1385gm. Maximum 3 flavors per half gallon.');
insert into foodItem values(1177,'Happy Pinwheel (6)','Blow a wish, spin the joy.');
insert into foodItem values(1178,'Ooh Chocolata! (6)','Let''s swim in the ponds of chocolate!');
insert into foodItem values(1179,'Ohana (6)','My 5 children in the bird''s nest.');
insert into foodItem values(1180,'Snowy Volcano (6)','Oh, the fun snowfight!');
insert into foodItem values(1181,'Pineapple Crush','Refreshing. Contains pineapple, guava n sorbet');
insert into foodItem values(1182,'Lychee Cooler','Refreshing. Best seller. Contains lychee, watermelon n sorbet');
insert into foodItem values(1183,'Water Works','Thirst quenching. Contains watermelon, pineapple, tropical juice n sorbet');
insert into foodItem values(1184,'Water Berry','Skin quenching. Best seller. Contains watermelon, strawberries, apple juice n sorbet');
insert into foodItem values(1185,'Berry Burst','Protects eyes. Contains strawberries, mixed berries, tropical juice n sorbet');
insert into foodItem values(1186,'Lychee Paradise','Best seller. Vitamin C. Contains lychee, lime, mango, apple Juice n sorbet');
insert into foodItem values(1187,'Zesty Melon','Vitamin C. Contains orange, watermelon, lime n sorbet');
insert into foodItem values(1188,'Strawberry Kiss','Vitamin C. Contains strawberries, tropical juice n low fat mixed berries yogurt');
insert into foodItem values(1189,'Pink Passion','Best seller. Destress n energies.Contains passion fruit, mango, strawberries, tropical juice n low fat mango yogurt');
insert into foodItem values(1190,'Mango Sensation','Fibre n digestion. Contains mango, banana, tropical juice n low fat mango yogurt');
insert into foodItem values(1191,'Hainan Steamed Chicken Rice','Hainan Steamed Chicken Rice');
insert into foodItem values(1192,'Oriental Chicken Chop with Nasi Minyak','Oriental Chicken Chop with Nasi Minyak');
insert into foodItem values(1193,'Chicken Katsu with Nasi Minyak','Chicken Katsu with Nasi Minyak');
insert into foodItem values(1194,'BBQ Chicken n Mushroom Dry Wantan Mee','BBQ Chicken n Mushroom Dry Wantan Mee');
insert into foodItem values(1195,'Hainan Steamed Chicken n Mushroom Dry Wantan Mee','Hainan Steamed Chicken n Mushroom Dry Wantan Mee');
insert into foodItem values(1196,'Egg Mayo Grilled Sandwich','Egg Mayo Grilled Sandwich');
insert into foodItem values(1197,'Chicken Mayo Grilled Sandwich','Chicken Mayo Grilled Sandwich');
insert into foodItem values(1198,'Chicken Meatloaf n Grilled Cheese Sandwich','Chicken Meatloaf n Grilled Cheese Sandwich');
insert into foodItem values(1199,'Tuna Sambal Grilled Sandwich','Tuna Sambal Grilled Sandwich');
insert into foodItem values(1200,'French Fries','French Fries');


select count(*) as TotalNumberOfFoodItem
from foodItem;