CREATE OR REPLACE PROCEDURE USER1.UPDATE_MENU_PRICE(
    IN_MENUID IN NUMBER, 
    IN_PRICE IN NUMBER 
) IS
    V_MENUNAME VARCHAR(50);
    V_OLD_PRICE NUMBER(7,2);
BEGIN
    
    SELECT m.MENUNAME, m.PRICE
    INTO V_MENUNAME, V_OLD_PRICE
    FROM MENU m 
    WHERE m.MENUID = IN_MENUID;

    UPDATE MENU 
    SET PRICE = IN_PRICE
    WHERE MENUID = IN_MENUID;

    DBMS_OUTPUT.PUT_LINE ('RECORD FOUND');
    DBMS_OUTPUT.PUT_LINE ('MENU NAME : ' || V_MENUNAME);    
    DBMS_OUTPUT.PUT_LINE ('OLD PRICE : ' || V_OLD_PRICE);
    DBMS_OUTPUT.PUT_LINE ('NEW PRICE : ' || IN_PRICE);
        
EXCEPTION
    WHEN NO_DATA_FOUND THEN 
        DBMS_OUTPUT.PUT_LINE ('RECORD NOT FOUND');
    
END UPDATE_MENU_PRICE;